import "@styles/globals.css";
import { Box, ChakraProvider } from "@chakra-ui/react";
import type { AppProps } from "next/app";
import styles from "@styles/Main.module.css";
import { useEffect, useState } from "react";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => setMounted(true), []);
  if (!mounted) return null;

  return (
    <ChakraProvider>
      <Head>
        <title>TronGPT: AI-Powered Interpreter for TRON</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
      <Box className={styles.ellipseOne}></Box>
      <Box className={styles.ellipseTwo}></Box>
    </ChakraProvider>
  );
}
