import "@styles/globals.css";
import { Box, ChakraProvider, extendTheme } from "@chakra-ui/react";
import type { AppProps } from "next/app";
import styles from "@styles/Main.module.css";
import { useEffect, useState } from "react";
import Head from "next/head";

const chakraTheme = extendTheme({
  components: {
    Tabs: {
      variants: {
        custom: {
          tab: {
            _selected: {
              color: "white",
              borderBottom: "1px solid white",
            },
          },
          tablist: {
            borderBottom: "solid 1px #969696 !important",
            color: "#969696",
          },
        },
      },
    },
  },
});

export default function App({ Component, pageProps }: AppProps) {
  const [mounted, setMounted] = useState(false);

  useEffect(() => setMounted(true), []);
  if (!mounted) return null;

  return (
    <ChakraProvider theme={chakraTheme}>
      <Head>
        <title>TARS: AI-Powered Interpreter for Binance Smart Chain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
      <Box className={styles.ellipseOne}></Box>
      <Box className={styles.ellipseTwo}></Box>
    </ChakraProvider>
  );
}
